# Generated by Django 6.0 on 2026-05-18 01:42

import django.db.models.deletion
import django.utils.timezone
import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("alpha3", models.CharField(blank=True, max_length=3, null=True, verbose_name="Codigo alpha-3")),
            ],
            options={
                "verbose_name": "Moneda",
                "verbose_name_plural": "Monedas",
            },
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(editable=False, null=True, verbose_name="Fecha de última modificación"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=expenses.models.expense_upload_path, verbose_name="Archivo"
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True, verbose_name="Resultado")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True, verbose_name="Fecha de fin"
                    ),
                ),
                ("fails", models.JSONField(blank=True, null=True, verbose_name="Errores")),
                (
                    "upload_type",
                    models.CharField(
                        blank=True,
                        choices=[("CREDIT_CARD", "Tarjeta de crédito"), ("SAVINGS_ACCOUNT", "Cuenta de ahorros")],
                        max_length=50,
                        null=True,
                        verbose_name="Tipo de subida",
                    ),
                ),
                (
                    "upload_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSING", "En proceso"),
                            ("DONE", "Hecho"),
                            ("FAILED", "Fallida"),
                        ],
                        default="PENDING",
                        max_length=20,
                        null=True,
                        verbose_name="Estado de la subida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subida de archivo",
                "verbose_name_plural": "Subidas de archivos",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("sign", models.IntegerField(choices=[(-1, "Debe (-)"), (1, "Haber (+)")], verbose_name="Signo")),
                (
                    "account_type",
                    models.CharField(
                        choices=[("FIX", "Fijo"), ("VAR", "Variable")],
                        default="VAR",
                        max_length=5,
                        verbose_name="Tipo de cuenta",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="expenses.account"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta",
                "verbose_name_plural": "Cuentas",
            },
        ),
        migrations.CreateModel(
            name="AccountAssociation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(max_length=100, verbose_name="Token para asociar")),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expenses.account")),
            ],
            options={
                "verbose_name": "Asociacion de cuenta",
                "verbose_name_plural": "Asociaciones de cuentas",
            },
        ),
        migrations.CreateModel(
            name="CurrencyConvert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exchange", models.DecimalField(decimal_places=4, max_digits=10, verbose_name="Tasa de conversión")),
                ("date", models.DateField(auto_now_add=True, verbose_name="Fecha de conversión")),
                ("currency", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expenses.currency")),
            ],
            options={
                "verbose_name": "Conversion de moneda",
                "verbose_name_plural": "Conversiones de monedas",
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=255, verbose_name="Descripción")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=13, verbose_name="Monto")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                ("monthly_payment", models.DecimalField(decimal_places=2, max_digits=13, verbose_name="Pago mensual")),
                ("months", models.SmallIntegerField(default=0, verbose_name="Meses")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("bank", models.CharField(max_length=100, verbose_name="Banco")),
                ("currency", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="expenses.currency")),
            ],
            options={
                "verbose_name": "Préstamo",
                "verbose_name_plural": "Préstamos",
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.IntegerField(verbose_name="Mes")),
                ("year", models.IntegerField(verbose_name="Año")),
                ("closed", models.BooleanField(default=False, verbose_name="Solo lectura")),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name="Monto total")),
                ("active", models.BooleanField(default=True, verbose_name="Es visible")),
            ],
            options={
                "verbose_name": "Periodo",
                "verbose_name_plural": "Periodos",
                "unique_together": {("month", "year")},
            },
        ),
        migrations.CreateModel(
            name="ProgramTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=13, verbose_name="Monto")),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True, verbose_name="Fecha de fin"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Programado")),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expenses.account")),
                ("currency", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expenses.currency")),
            ],
            options={
                "verbose_name": "Transacción programada",
                "verbose_name_plural": "Transacciones programadas",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[("MOVIES", "Películas"), ("MUSIC", "Música"), ("BOOKS", "Libros"), ("OTHER", "Otros")],
                        default="MOVIES",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("monthly_payment", models.DecimalField(decimal_places=2, max_digits=13, verbose_name="Pago mensual")),
                ("currency", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="expenses.currency")),
            ],
            options={
                "verbose_name": "Suscripción",
                "verbose_name_plural": "Suscripciones",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(editable=False, null=True, verbose_name="Fecha de última modificación"),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=13, verbose_name="Monto")),
                ("description", models.CharField(blank=True, max_length=255, null=True, verbose_name="Descripción")),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True, verbose_name="Fecha de pago"
                    ),
                ),
                (
                    "local_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=13, verbose_name="Monto local"
                    ),
                ),
                ("identifier", models.CharField(blank=True, max_length=64, null=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expenses.account")),
                ("currency", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expenses.currency")),
                ("period", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expenses.period")),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="expenses.upload"
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción",
                "verbose_name_plural": "Transacciones",
            },
        ),
    ]
