# Generated by Django 6.0 on 2026-03-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0034_upload_end_date_upload_start_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadData",
        ),
    ]
