# Generated by Django 6.0 on 2026-03-01 19:03

import django.db.models.deletion
import django.utils.timezone
import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0034_upload_end_date_upload_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(editable=False, null=True, verbose_name="Fecha de última modificación"),
                ),
                (
                    "input_file",
                    models.FileField(
                        blank=True, null=True, upload_to=expenses.models.expense_upload_path, verbose_name="Archivo CSV"
                    ),
                ),
                (
                    "output_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=expenses.models.expense_upload_path,
                        verbose_name="Archivo JSON",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True, verbose_name="Fecha de fin"
                    ),
                ),
                (
                    "status_upload",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSING", "Procesando"),
                            ("ERROR", "Error"),
                            ("FINISHED", "Terminado"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado del proceso",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="upload_file",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="expenses.uploadfile"
            ),
        ),
        migrations.DeleteModel(
            name="UploadData",
        ),
    ]
