# Generated by Django 6.0 on 2026-05-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0035_delete_uploaddata"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="fails",
            field=models.JSONField(blank=True, null=True, verbose_name="Errores"),
        ),
    ]
