# Generated by Django 6.0 on 2026-05-10 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0036_upload_fails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upload",
            name="data",
        ),
        migrations.RemoveField(
            model_name="upload",
            name="dimension",
        ),
        migrations.RemoveField(
            model_name="upload",
            name="parameters",
        ),
    ]
