# Generated by Django 6.0 on 2026-05-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0037_remove_upload_data_remove_upload_dimension_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="upload_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pendiente"),
                    ("PROCESSING", "En proceso"),
                    ("DONE", "Hecho"),
                    ("FAILED", "Fallida"),
                ],
                default="PENDING",
                max_length=20,
                null=True,
                verbose_name="Estado de la subida",
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="upload_type",
            field=models.CharField(
                blank=True,
                choices=[("CREDIT_CARD", "Tarjeta de crédito"), ("SAVINGS_ACCOUNT", "Cuenta de ahorros")],
                max_length=50,
                null=True,
                verbose_name="Tipo de subida",
            ),
        ),
    ]
