# Generated by Django 6.0 on 2026-05-18 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expenses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("period", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expenses.period")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "ordering": ["-period"],
                "unique_together": {("user", "period")},
            },
        ),
        migrations.CreateModel(
            name="BudgetAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("budget_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("expense_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="expenses.account"
                    ),
                ),
                ("budget", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="budgets.budget")),
            ],
            options={
                "verbose_name": "Asignacion de presupuesto",
                "verbose_name_plural": "Asignaciones de presupuesto",
                "unique_together": {("budget", "account")},
            },
        ),
    ]
